### ISSUE TITLE
Start as Enabled

### ISSUE THREAD

**Issue by mastrolube** [WithoutHair/Disable-Content-Security-Policy#1]
Hi there, I'm not a JS coder.
How can I start this as already active?

I'm running some selenium test and got a CSP block of my get_har script.
This workaround works well but I need to start it as already active.

I've messed a little bit with the code but I was not able to do it :D

Any suggestion? Thanks!

**Comment by WithoutHair** [comment]
Hello.Sorry to keep you waiting for so long.
So you wanna rewrite the code and make it always active but not have to click the icon at every page.Is this what you mean?

In the line 43,you have to set the urlFilter's value with *.
And you click the icon,it works at every page until you close the explorer.

In the function isCSPDisabled,remove variables urls and url.
Rewrite it to a funtion that checks the variable rules' length is 0 or not.

That's all.

**Comment by WithoutHair** [comment]
I made a mistake.You also have to remove the if condition in the forEach method,which is in line 52.

I tried it and made a simple test just now.And I'm considering bringing the feature to it.
