### ISSUE TITLE
Only works after refreshing the page

### ISSUE THREAD

**Issue by skyfighteer** [WithoutHair/Disable-Content-Security-Policy#2]
The current implementation only works after opening a site, clicking on icon, then reloading the site.

**Comment by WithoutHair** [comment]
It's because when the extension isn't working, page will be loaded successfully with CSP enabled.

After you refresh the site,explorer will request HTML document from server again.But rule has been added,so CSP is disabled.That's how it works.

I'm thinking about adding a option to control if it'll always be active on every site.What do u think of it?

**Comment by skyfighteer** [comment]
I know how it works, but I wonder how you'd fix first time load of site, even if would work on every site by default.

I couldnt find a way to add rules synchronously on headers received, like with webrequest.

What do you think?

**Comment by WithoutHair** [comment]
No way bro.I checked the documentation again.There isn't something that can make headers updated on a loaded site.

Actually I have realized this problem when I was developing.After the extension is enabled,it's impossible to make it effective on tabs are already opened,which conform to logic I think.

So the method I mentioned before I'd say it's a compromise,and one user also asked me how to implement that.

**Comment by skyfighteer** [comment]
There has never been a way to reload headers, that is not a problem.

However, the way developers handled this with webrequest was to change headers synchronously with the blocking option early onHeadersReceived, then let the page finish loading.

However, webrequest was deprecated with manifest V3, so other than reloading the page, there is no way to have the new headers on first load.

**Comment by WithoutHair** [comment]
What do you mean deprecated?
All the api I use belongs to V3.The train of thoughts is the same,though.

**Comment by skyfighteer** [comment]
Sorry, rephrased my answer.

**Comment by WithoutHair** [comment]
Okay I think I know what you mean "first time load of site" now...

I was about to say much to express my complicated feelings but let's make a long story short.

You just need to set the key 'urlFilter' with *.
